import nodemailer from 'nodemailer';
/**
 * Sends a notification email to the administrator when any form is filled.
 * @param formType Type of form (e.g. 'volunteer', 'contact', 'donation', 'admission', etc.)
 * @param formData Key-value pair of the form fields filled by the user.
 */
export const sendNotificationEmail = async (formType, formData) => {
    const emailUser = process.env.EMAIL_USER;
    const emailPass = process.env.EMAIL_PASS;
    const smtpHost = process.env.SMTP_HOST || 'smtp.gmail.com';
    const smtpPort = parseInt(process.env.SMTP_PORT || '587');
    const targetEmail = 'ashifansari04704@gmail.com';
    // Format email body
    let formattedDetails = '';
    for (const [key, value] of Object.entries(formData)) {
        // Format keys (e.g. donorName -> Donor Name)
        const formattedKey = key
            .replace(/([A-Z])/g, ' $1')
            .replace(/^./, (str) => str.toUpperCase());
        formattedDetails += `<strong>${formattedKey}:</strong> ${value}<br/>`;
    }
    const subject = `[NGO Form Submission] New ${formType.toUpperCase()} Details`;
    const htmlContent = `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 5px; background-color: #ffffff;">
      <h2 style="color: #0055a5; border-bottom: 2px solid #0055a5; padding-bottom: 10px; margin-top: 0;">
        New Form Submission Received
      </h2>
      <p style="font-size: 14px; color: #333333;">
        A user has successfully submitted a form on the Triyambakam Gurukulam website.
      </p>
      <div style="background-color: #f9f9f9; padding: 15px; border-left: 4px solid #ff6600; margin: 20px 0; border-radius: 3px; font-size: 14px; line-height: 1.6; color: #333333;">
        <strong>Form Purpose:</strong> ${formType.toUpperCase()}<br/>
        <hr style="border: 0; border-top: 1px solid #e0e0e0; margin: 10px 0;" />
        ${formattedDetails}
      </div>
      <p style="font-size: 12px; color: #777777; margin-top: 30px; border-top: 1px solid #e0e0e0; padding-top: 10px;">
        This email was automatically generated by the Triyambakam Gurukulam Association website backend.
      </p>
    </div>
  `;
    console.log(`[Email Service] Form Type: ${formType}`);
    console.log(`[Email Service] Destination: ${targetEmail}`);
    console.log(`[Email Service] Payload:`, formData);
    // If environment variables are missing, safely log to console and return success: true for user experience
    if (!emailUser || !emailPass) {
        console.warn('[Email Service] WARNING: EMAIL_USER or EMAIL_PASS environment variables are not set. Local fallback triggered (Logged details to stdout).');
        return { success: true, logged: true };
    }
    try {
        const transporter = nodemailer.createTransport({
            host: smtpHost,
            port: smtpPort,
            secure: smtpPort === 465,
            auth: {
                user: emailUser,
                pass: emailPass,
            },
        });
        const info = await transporter.sendMail({
            from: `"Gurukulam Agra Notifications" <${emailUser}>`,
            to: targetEmail,
            subject: subject,
            html: htmlContent,
        });
        console.log(`[Email Service] Email sent successfully: ${info.messageId}`);
        return { success: true, messageId: info.messageId };
    }
    catch (error) {
        console.error('[Email Service] Error occurred while sending email:', error);
        return { success: false, error: error };
    }
};
